"""add_active_branch_detail_table

Revision ID: dd7fc9193fd9
Revises: 82aa768422cc
Create Date: 2026-01-17 20:54:49.642657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7fc9193fd9'
down_revision: Union[str, None] = '82aa768422cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_branch_detail',
    sa.Column('institution_code', sa.String(length=50), nullable=False, comment='营业部代码'),
    sa.Column('institution_name', sa.String(length=200), nullable=True, comment='营业部名称'),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('change_percent', sa.Numeric(precision=8, scale=2), nullable=True, comment='涨跌幅'),
    sa.Column('buy_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='买入金额'),
    sa.Column('sell_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='卖出金额'),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='净额'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='上榜原因'),
    sa.Column('after_1d', sa.Numeric(precision=8, scale=2), nullable=True, comment='1日后涨跌幅'),
    sa.Column('after_2d', sa.Numeric(precision=8, scale=2), nullable=True, comment='2日后涨跌幅'),
    sa.Column('after_3d', sa.Numeric(precision=8, scale=2), nullable=True, comment='3日后涨跌幅'),
    sa.Column('after_5d', sa.Numeric(precision=8, scale=2), nullable=True, comment='5日后涨跌幅'),
    sa.Column('after_10d', sa.Numeric(precision=8, scale=2), nullable=True, comment='10日后涨跌幅'),
    sa.Column('after_20d', sa.Numeric(precision=8, scale=2), nullable=True, comment='20日后涨跌幅'),
    sa.Column('after_30d', sa.Numeric(precision=8, scale=2), nullable=True, comment='30日后涨跌幅'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_code', 'date', 'stock_code', name='uq_active_branch_detail'),
    comment='活跃营业部交易详情表'
    )
    op.create_index(op.f('ix_active_branch_detail_date'), 'active_branch_detail', ['date'], unique=False)
    op.create_index(op.f('ix_active_branch_detail_id'), 'active_branch_detail', ['id'], unique=False)
    op.create_index(op.f('ix_active_branch_detail_institution_code'), 'active_branch_detail', ['institution_code'], unique=False)
    op.create_index(op.f('ix_active_branch_detail_institution_name'), 'active_branch_detail', ['institution_name'], unique=False)
    op.create_index(op.f('ix_active_branch_detail_stock_code'), 'active_branch_detail', ['stock_code'], unique=False)
    op.drop_index('idx_emotional_cycle_date', table_name='emotional_cycle')
    op.drop_index('ix_emotional_cycle_date', table_name='emotional_cycle')
    op.drop_index('ix_emotional_cycle_id', table_name='emotional_cycle')
    op.drop_table('emotional_cycle')
    op.alter_column('active_branch', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_active_branch_id'), 'active_branch', ['id'], unique=False)
    op.drop_column('active_branch', 'updated_at')
    op.alter_column('concept_fund_flow', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_concept_fund_flow_id'), 'concept_fund_flow', ['id'], unique=False)
    op.create_table_comment(
        'concept_fund_flow',
        '概念资金流表（stock_fund_flow_concept 即时）',
        existing_comment=None,
        schema=None
    )
    op.drop_column('concept_fund_flow', 'updated_at')
    op.alter_column('industry_fund_flow', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_industry_fund_flow_id'), 'industry_fund_flow', ['id'], unique=False)
    op.create_table_comment(
        'industry_fund_flow',
        '行业/概念资金流表（stock_fund_flow_industry 即时）',
        existing_comment=None,
        schema=None
    )
    op.drop_column('industry_fund_flow', 'updated_at')
    op.alter_column('institution_trading_statistics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_institution_trading_statistics_id'), 'institution_trading_statistics', ['id'], unique=False)
    op.drop_column('institution_trading_statistics', 'updated_at')
    op.alter_column('lhb_detail', 'concept',
               existing_type=sa.VARCHAR(length=200),
               comment='概念板块',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'date',
               existing_type=sa.DATE(),
               comment='上榜日期',
               existing_nullable=False)
    op.alter_column('lhb_hot_institution', 'institution_name',
               existing_type=sa.VARCHAR(length=200),
               comment='营业部名称',
               existing_nullable=False)
    op.alter_column('lhb_hot_institution', 'institution_code',
               existing_type=sa.VARCHAR(length=50),
               comment='营业部代码',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'buy_stock_count',
               existing_type=sa.INTEGER(),
               comment='买入个股数',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'sell_stock_count',
               existing_type=sa.INTEGER(),
               comment='卖出个股数',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'buy_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='买入总金额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'sell_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='卖出总金额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'net_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总买卖净额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'buy_stocks',
               existing_type=sa.TEXT(),
               comment='买入股票列表',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_lhb_hot_institution_id'), 'lhb_hot_institution', ['id'], unique=False)
    op.create_table_comment(
        'lhb_hot_institution',
        '龙虎榜机构游资榜（营业部榜）',
        existing_comment='活跃营业部',
        schema=None
    )
    op.drop_column('lhb_hot_institution', 'updated_at')
    op.drop_index('idx_lhb_institution_flag', table_name='lhb_institution')
    op.create_index(op.f('ix_lhb_institution_flag'), 'lhb_institution', ['flag'], unique=False)
    op.drop_index('idx_concept_code', table_name='stock_concept')
    op.drop_index('idx_concept_level', table_name='stock_concept')
    op.drop_index('idx_concept_name', table_name='stock_concept')
    op.drop_index('idx_concept_name_level_parent', table_name='stock_concept')
    op.drop_index('idx_concept_parent', table_name='stock_concept')
    op.drop_index('idx_concept_path', table_name='stock_concept')
    op.drop_constraint('stock_concept_name_key', 'stock_concept', type_='unique')
    op.create_table_comment(
        'stock_concept',
        '股票概念板块表（支持2-3级层级）',
        existing_comment='股票概念板块表',
        schema=None
    )
    op.alter_column('stock_concept_mapping', 'concept_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='概念板块ID',
               existing_nullable=False)
    op.drop_index('idx_scm_concept', table_name='stock_concept_mapping')
    op.drop_index('idx_scm_stock', table_name='stock_concept_mapping')
    op.drop_constraint('uq_stock_concept_mapping', 'stock_concept_mapping', type_='unique')
    op.create_index(op.f('ix_stock_concept_mapping_concept_id'), 'stock_concept_mapping', ['concept_id'], unique=False)
    op.create_index(op.f('ix_stock_concept_mapping_stock_name'), 'stock_concept_mapping', ['stock_name'], unique=False)
    op.create_table_comment(
        'stock_concept_mapping',
        '股票概念板块通用关联表',
        existing_comment='股票概念板块通用关联表（核心表，供所有模块使用）',
        schema=None
    )
    op.alter_column('stock_fund_flow', 'is_limit_up',
               existing_type=sa.BOOLEAN(),
               comment='是否涨停',
               existing_nullable=True)
    op.alter_column('stock_fund_flow', 'is_lhb',
               existing_type=sa.BOOLEAN(),
               comment='是否龙虎榜',
               existing_nullable=True)
    op.drop_index('ix_task_execution_start_time', table_name='task_execution')
    op.drop_index('ix_task_execution_task_type_start_time', table_name='task_execution')
    op.alter_column('trader', 'aka',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='操作风格',
               existing_nullable=True)
    op.alter_column('trader', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('trader_name_key', 'trader', type_='unique')
    op.drop_index('ix_trader_name', table_name='trader')
    op.create_index(op.f('ix_trader_name'), 'trader', ['name'], unique=True)
    op.create_index(op.f('ix_trader_id'), 'trader', ['id'], unique=False)
    op.drop_column('trader', 'updated_at')
    op.alter_column('trader_branch', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trader_branch_id'), 'trader_branch', ['id'], unique=False)
    op.create_table_comment(
        'trader_branch',
        '游资与营业部映射表（极简）',
        existing_comment=None,
        schema=None
    )
    op.drop_column('trader_branch', 'updated_at')
    op.alter_column('trader_branch_history', 'institution_code',
               existing_type=sa.VARCHAR(length=50),
               comment='营业部代码',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'institution_name',
               existing_type=sa.VARCHAR(length=200),
               comment='营业部名称',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'stock_code',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'change_percent',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'buy_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='买入金额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'sell_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='卖出金额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'net_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='净额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'reason',
               existing_type=sa.VARCHAR(length=200),
               comment='上榜原因',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_1d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='1日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_2d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='2日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_3d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='3日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_5d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='5日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_10d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='10日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_20d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='20日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_30d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='30日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trader_branch_history_id'), 'trader_branch_history', ['id'], unique=False)
    op.create_table_comment(
        'trader_branch_history',
        '游资营业部历史交易明细表',
        existing_comment=None,
        schema=None
    )
    op.drop_column('trader_branch_history', 'updated_at')
    op.alter_column('trading_calendar', 'date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'strategy',
               existing_type=sa.VARCHAR(length=20),
               comment='策略：低吸/排板',
               existing_comment='策略：低吸/打板',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'price',
               existing_type=sa.NUMERIC(),
               comment='价格',
               existing_nullable=True)
    op.alter_column('trading_calendar', 'is_executed',
               existing_type=sa.BOOLEAN(),
               comment='是否执行策略',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('trading_calendar_concept', 'trading_calendar_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='交易日历ID',
               existing_nullable=False)
    op.alter_column('trading_calendar_concept', 'concept_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='概念板块ID',
               existing_nullable=False)
    op.drop_index('idx_tcc_calendar', table_name='trading_calendar_concept')
    op.drop_index('idx_tcc_concept', table_name='trading_calendar_concept')
    op.drop_constraint('uq_trading_calendar_concept', 'trading_calendar_concept', type_='unique')
    op.create_index(op.f('ix_trading_calendar_concept_concept_id'), 'trading_calendar_concept', ['concept_id'], unique=False)
    op.create_index(op.f('ix_trading_calendar_concept_trading_calendar_id'), 'trading_calendar_concept', ['trading_calendar_id'], unique=False)
    op.alter_column('zt_pool_down', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_zt_pool_down_id'), 'zt_pool_down', ['id'], unique=False)
    op.create_table_comment(
        'zt_pool_down',
        '跌停池表',
        existing_comment='跌停股票池',
        schema=None
    )
    op.drop_column('zt_pool_down', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zt_pool_down', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'zt_pool_down',
        '跌停股票池',
        existing_comment='跌停池表',
        schema=None
    )
    op.drop_index(op.f('ix_zt_pool_down_id'), table_name='zt_pool_down')
    op.alter_column('zt_pool_down', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trading_calendar_concept_trading_calendar_id'), table_name='trading_calendar_concept')
    op.drop_index(op.f('ix_trading_calendar_concept_concept_id'), table_name='trading_calendar_concept')
    op.create_unique_constraint('uq_trading_calendar_concept', 'trading_calendar_concept', ['trading_calendar_id', 'concept_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_tcc_concept', 'trading_calendar_concept', ['concept_id'], unique=False)
    op.create_index('idx_tcc_calendar', 'trading_calendar_concept', ['trading_calendar_id'], unique=False)
    op.alter_column('trading_calendar_concept', 'concept_id',
               existing_type=sa.INTEGER(),
               comment='概念板块ID',
               existing_nullable=False)
    op.alter_column('trading_calendar_concept', 'trading_calendar_id',
               existing_type=sa.INTEGER(),
               comment='交易日历ID',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'is_executed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否执行策略',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('trading_calendar', 'price',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='价格',
               existing_nullable=True)
    op.alter_column('trading_calendar', 'strategy',
               existing_type=sa.VARCHAR(length=20),
               comment='策略：低吸/打板',
               existing_comment='策略：低吸/排板',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=False)
    op.alter_column('trading_calendar', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.add_column('trader_branch_history', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'trader_branch_history',
        existing_comment='游资营业部历史交易明细表',
        schema=None
    )
    op.drop_index(op.f('ix_trader_branch_history_id'), table_name='trader_branch_history')
    op.alter_column('trader_branch_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trader_branch_history', 'after_30d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='30日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_20d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='20日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_10d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='10日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_5d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='5日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_3d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='3日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_2d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='2日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'after_1d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='1日后涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'reason',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='上榜原因',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'net_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='净额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'sell_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='卖出金额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'buy_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='买入金额',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'change_percent',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('trader_branch_history', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'stock_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'institution_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='营业部名称',
               existing_nullable=False)
    op.alter_column('trader_branch_history', 'institution_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='营业部代码',
               existing_nullable=True)
    op.add_column('trader_branch', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'trader_branch',
        existing_comment='游资与营业部映射表（极简）',
        schema=None
    )
    op.drop_index(op.f('ix_trader_branch_id'), table_name='trader_branch')
    op.alter_column('trader_branch', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('trader', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_trader_id'), table_name='trader')
    op.drop_index(op.f('ix_trader_name'), table_name='trader')
    op.create_index('ix_trader_name', 'trader', ['name'], unique=False)
    op.create_unique_constraint('trader_name_key', 'trader', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('trader', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trader', 'aka',
               existing_type=sa.TEXT(),
               comment='操作风格',
               existing_comment='描述',
               existing_nullable=True)
    op.create_index('ix_task_execution_task_type_start_time', 'task_execution', ['task_type', 'start_time'], unique=False)
    op.create_index('ix_task_execution_start_time', 'task_execution', ['start_time'], unique=False)
    op.alter_column('stock_fund_flow', 'is_lhb',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否龙虎榜',
               existing_nullable=True)
    op.alter_column('stock_fund_flow', 'is_limit_up',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否涨停',
               existing_nullable=True)
    op.create_table_comment(
        'stock_concept_mapping',
        '股票概念板块通用关联表（核心表，供所有模块使用）',
        existing_comment='股票概念板块通用关联表',
        schema=None
    )
    op.drop_index(op.f('ix_stock_concept_mapping_stock_name'), table_name='stock_concept_mapping')
    op.drop_index(op.f('ix_stock_concept_mapping_concept_id'), table_name='stock_concept_mapping')
    op.create_unique_constraint('uq_stock_concept_mapping', 'stock_concept_mapping', ['stock_name', 'concept_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_scm_stock', 'stock_concept_mapping', ['stock_name'], unique=False)
    op.create_index('idx_scm_concept', 'stock_concept_mapping', ['concept_id'], unique=False)
    op.alter_column('stock_concept_mapping', 'concept_id',
               existing_type=sa.INTEGER(),
               comment='概念板块ID',
               existing_nullable=False)
    op.create_table_comment(
        'stock_concept',
        '股票概念板块表',
        existing_comment='股票概念板块表（支持2-3级层级）',
        schema=None
    )
    op.create_unique_constraint('stock_concept_name_key', 'stock_concept', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_concept_path', 'stock_concept', ['path'], unique=False)
    op.create_index('idx_concept_parent', 'stock_concept', ['parent_id'], unique=False)
    op.create_index('idx_concept_name_level_parent', 'stock_concept', ['name', 'level', 'parent_id'], unique=True)
    op.create_index('idx_concept_name', 'stock_concept', ['name'], unique=False)
    op.create_index('idx_concept_level', 'stock_concept', ['level'], unique=False)
    op.create_index('idx_concept_code', 'stock_concept', ['code'], unique=False)
    op.drop_index(op.f('ix_lhb_institution_flag'), table_name='lhb_institution')
    op.create_index('idx_lhb_institution_flag', 'lhb_institution', ['flag'], unique=False)
    op.add_column('lhb_hot_institution', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'lhb_hot_institution',
        '活跃营业部',
        existing_comment='龙虎榜机构游资榜（营业部榜）',
        schema=None
    )
    op.drop_index(op.f('ix_lhb_hot_institution_id'), table_name='lhb_hot_institution')
    op.alter_column('lhb_hot_institution', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lhb_hot_institution', 'buy_stocks',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='买入股票列表',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'net_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='总买卖净额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'sell_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='卖出总金额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'buy_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='买入总金额',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'sell_stock_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='卖出个股数',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'buy_stock_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='买入个股数',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'institution_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='营业部代码',
               existing_nullable=True)
    op.alter_column('lhb_hot_institution', 'institution_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='营业部名称',
               existing_nullable=False)
    op.alter_column('lhb_hot_institution', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='上榜日期',
               existing_nullable=False)
    op.alter_column('lhb_detail', 'concept',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='概念板块',
               existing_nullable=True)
    op.add_column('institution_trading_statistics', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_institution_trading_statistics_id'), table_name='institution_trading_statistics')
    op.alter_column('institution_trading_statistics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('industry_fund_flow', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'industry_fund_flow',
        existing_comment='行业/概念资金流表（stock_fund_flow_industry 即时）',
        schema=None
    )
    op.drop_index(op.f('ix_industry_fund_flow_id'), table_name='industry_fund_flow')
    op.alter_column('industry_fund_flow', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('concept_fund_flow', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'concept_fund_flow',
        existing_comment='概念资金流表（stock_fund_flow_concept 即时）',
        schema=None
    )
    op.drop_index(op.f('ix_concept_fund_flow_id'), table_name='concept_fund_flow')
    op.alter_column('concept_fund_flow', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('active_branch', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_active_branch_id'), table_name='active_branch')
    op.alter_column('active_branch', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('emotional_cycle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False, comment='日期'),
    sa.Column('szbl', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='上涨比例'),
    sa.Column('lbjs', sa.INTEGER(), autoincrement=False, nullable=True, comment='连板家数'),
    sa.Column('ylgd', sa.INTEGER(), autoincrement=False, nullable=True, comment='压力高度'),
    sa.Column('zxgd', sa.INTEGER(), autoincrement=False, nullable=True, comment='最新高度'),
    sa.Column('dmqx', sa.INTEGER(), autoincrement=False, nullable=True, comment='大面情绪'),
    sa.Column('drqx', sa.INTEGER(), autoincrement=False, nullable=True, comment='大肉情绪'),
    sa.Column('ztjs', sa.INTEGER(), autoincrement=False, nullable=True, comment='涨停家数'),
    sa.Column('dbcgl', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='打板成功率'),
    sa.Column('dtjs', sa.INTEGER(), autoincrement=False, nullable=True, comment='跌停家数'),
    sa.Column('ygmc', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='股票名称'),
    sa.PrimaryKeyConstraint('id', name='emotional_cycle_pkey'),
    comment='情绪周期表'
    )
    op.create_index('ix_emotional_cycle_id', 'emotional_cycle', ['id'], unique=False)
    op.create_index('ix_emotional_cycle_date', 'emotional_cycle', ['date'], unique=False)
    op.create_index('idx_emotional_cycle_date', 'emotional_cycle', ['date'], unique=False)
    op.drop_index(op.f('ix_active_branch_detail_stock_code'), table_name='active_branch_detail')
    op.drop_index(op.f('ix_active_branch_detail_institution_name'), table_name='active_branch_detail')
    op.drop_index(op.f('ix_active_branch_detail_institution_code'), table_name='active_branch_detail')
    op.drop_index(op.f('ix_active_branch_detail_id'), table_name='active_branch_detail')
    op.drop_index(op.f('ix_active_branch_detail_date'), table_name='active_branch_detail')
    op.drop_table('active_branch_detail')
    # ### end Alembic commands ###

